name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: sagarbawanthade/abhinavs-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Create dynamic tag from short SHA
      - name: Set TAG
        id: tag
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$TAG

      - name: SSH and Deploy on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/Abhinasv-s-Backend
            docker compose down
            sed -i 's|sagarbawanthade/abhinavs-backend:.*|sagarbawanthade/abhinavs-backend:${{ env.TAG }}|' docker-compose.yaml
            docker compose pull
            docker compose up -d
